### ISSUE TITLE
Admin dashboard should display running simulations and their participant IDs

### ISSUE THREAD

**Issue by jorgearanda** [jorgearanda/fish#111]
There are some set-ups where the researcher is interested in having participants know who is working/competing with whom. Having that information spelled out in the main admin window should help them achieve this.

**Comment by btruhand** [comment]
Norman have you started working on this? I was planning to do this one and #130

**Comment by nsue** [comment]
Oh, no I haven't started -- you can go right ahead. I'm reassigning this issue to you.

**Comment by btruhand** [comment]
Jorge, do you want it so that the experimenters get the contents of the display based on when he/she enters the dashboard, or do you want it so that the contents of the display also has all the simulations that are still running but started before the experimenter got to the dashboard?

**Comment by jorgearanda** [comment]
All--including those started before the experimenter logged in.

**Comment by btruhand** [comment]
via PR https://github.com/jorgearanda/fish/pull/192
