### ISSUE TITLE
Interrupted simulations should be reported in the experimenter dashboard

### ISSUE THREAD

**Issue by jorgearanda** [jorgearanda/fish#144]

**Comment by btruhand** [comment]
What do you exactly mean by 'interrupted' Jorge?

**Comment by jorgearanda** [comment]
Abandoned--we detected that the participant disconnected before the end of the simulation.

**Comment by btruhand** [comment]
So for example the participant closed the tab for the simulation? Out of curiosity, what currently happens to the simulation if this happens?

**Comment by jorgearanda** [comment]
Yeah--when that happens, currently, the simulation keeps playing out until its time runs out.

**Comment by btruhand** [comment]
Should participants who left before the simulation officially starts i.e before the correct number of participants have arrived and/or finished reading the rules also be reported?

**Comment by jorgearanda** [comment]
> Should participants who left before the simulation officially starts i.e before the correct number of participants have arrived and/or finished reading the rules also be reported?

No

> Also, do you want those participants who disconnected during the setup phase of the simulation to also be reported? And if so, do you want the experimenters to be able to distinguish at which stage a participant disconnected i.e during the setup phase or during the actual run of the simulation

Once the simulation begins the countdown to start (after everybody has said that they've read the rules) they should be counted--but not before.

**Comment by jorgearanda** [comment]
Closed by PR #192
