### ISSUE TITLE
[User] Colour Scheme

### ISSUE THREAD

**Issue by James-Firth** [jorgearanda/fish#160]
We should decide on a new colour scheme to be a little more visually pleasing.

Perhaps these? We discussed blues/greens being nice (and working well with the ocean theme!)

![palette colours](http://i.imgur.com/ktaD3iu.jpg)
http://www.materialpalette.com/light-blue/green 
```sass
/* Palette generated by Material Palette - materialpalette.com/light-blue/green */

$darkPrimaryColor:   #0288D1
$primaryColor:       #03A9F4
$lightPrimaryColor:  #B3E5FC
$textPrimaryColor:   #FFFFFF
$accentColor:        #4CAF50
$primaryTextColor:   #212121
$secondaryTextColor: #727272
$dividerColor:       #B6B6B6
```

**Comment by jorgearanda** [comment]
Great palette, yeah.
