### ISSUE TITLE
Release Naming Conventions?

### ISSUE THREAD

**Issue by James-Firth** [jorgearanda/fish#162]
I think we should name each release after a type of fish/aquatic creature with an <adjective><animal> alphabetical order similar to ubuntu releases.

Thoughts?

**Comment by jorgearanda** [comment]
Awesome idea!

Also, the release name/version should be included in the simulation run results downloaded by experimenters.

So, A: Anemone?

**Comment by James-Firth** [comment]
Ardent Anemone perhaps?

Though hm it seems they're technically 'sea anemones' but I'm fine with using it still personally.

**Comment by jorgearanda** [comment]
What about Ballsy Barracuda for the release after? :-)
