### ISSUE TITLE
Custom Icon Font

### ISSUE THREAD

**Issue by James-Firth** [jorgearanda/fish#164]
Since we're going to wait some icons, but mostly non-standard ones (like fish and boats and whatnot) for web applications I think we should make a custom icon font. I've wanted to put fish icons in some spots but using `<img>` tags is much more annoying than an icon font in my opinion.

This site lets us combine current popular icon fonts but also drag in SVGs: http://fontello.com/ 
I used this site to find some fish-related SVGs: http://www.flaticon.com/

Thoughts?

**Comment by jorgearanda** [comment]
Yeah, perfect!
