### ISSUE TITLE
Ocean Status Table - Experimenter configurable ordering

### ISSUE THREAD

**Issue by James-Firth** [jorgearanda/fish#172]
The experimenters should be able to configure the ordering of the fishers in the ocean status table.

Ordering options should include:
- [ ] Static; current user on top
- [ ] Static; current user in middle
- [ ] Static; current user on bottom
- [ ] Dynamic; descending by fish caught this season
- [ ] Dynamic; descending by fish caught overall
- [ ] Dynamic; descending by $ this season
- [ ] Dynamic; descending by $ overall

**Comment by jorgearanda** [comment]
Clarifying on "static", how about the following:

* Static; current user on top
* Static; current user on bottom
* Dynamic; descending by fish caught this season
* Dynamic; descending by fish caught overall
* Dynamic; descending by $ this season
* Dynamic; descending by $ overall

**Comment by James-Firth** [comment]
:+1: Looks good to me, I'll edit the first issue to keep the info at the top. I think I would also add a "Static; current user in middle"

**Comment by jorgearanda** [comment]
Cool!
