### ISSUE TITLE
Participants using smaller screen sizes have the info table columns cropped down

### ISSUE THREAD

**Issue by jorgearanda** [jorgearanda/fish#175]
We should expand the space used by the table (while decreasing the amount used by the left-hand, ocean panel), and make a more efficient use of white space to make sure the information all fits and is readable. Ideally we should support screen sizes of down to 1024x768--if that's too unrealistic we'll reevaluate.

**Comment by jorgearanda** [comment]
![screen shot 2015-01-19 at 8 31 26 pm](https://cloud.githubusercontent.com/assets/730633/5812243/f3813668-a01a-11e4-9766-84ac54eda02e.png)

**Comment by nsue** [comment]
Notes:
- perhaps smaller font size and no bold
