### ISSUE TITLE
All simulation parameters should be disabled after the microworld is activated

### ISSUE THREAD

**Issue by jorgearanda** [jorgearanda/fish#186]
Most text boxes in the microworld page are disabled once the microworld is active. However, a bunch of things aren't:

- [ ] Checkboxes
- [ ] Radio buttons
- [ ] Some bot behaviour parameters

Even though any updates wouldn't be saved, we should not lead researchers to believe they can change any parameters.

**Comment by James-Firth** [comment]
Ah, I saw the Bot Behaviour was editable, didn't realize it was a bug though.

Do we want this to just be a client-side disable or server-side too? If it's just client-side I can whip up a patch tomorrow to fix this.

**Comment by jorgearanda** [comment]
Only client side is necessary :-)

**Comment by nsue** [comment]
Oh, James, if you're eager to do this, you can take this one instead. I just pressed the self-assign button by habit haha.

**Comment by James-Firth** [comment]
@jorgearanda Okay great

@nsue Haha fair enough. Sure I'll grab it since I don't have much at the moment

**Comment by James-Firth** [comment]
@jorgearanda I was working on this and it looks like the uniform bot behaviour doesn't get saved or at least loaded during the populatePage() method in public/js/microworld.js 

Should I make a new issue for dealing with that or just deal with it in this issue? (As far as I can tell my fix for this issue will work once the uniform stuff is saved/loaded properly)

**Comment by James-Firth** [comment]
Pull #196 will close this issue. However the issue of uniformity not being saved is still present. I guess I'll open a new issue for it.
