### ISSUE TITLE
Fishers are not getting automatically returned to port

### ISSUE THREAD

**Issue by jorgearanda** [jorgearanda/fish#194]
When a season ends with fishers still out, they are not returned to port on their own. The button in their UI still reads "Return to port", when it should be reset as if they were already in port (along with their status)

**Comment by jorgearanda** [comment]
@James-Firth, @nsue, would one of you like to take this?

**Comment by James-Firth** [comment]
I could take a look at that, not sure if I'll have time tonight but it'll be done by the end of Saturday at the latest.
