### ISSUE TITLE
Add a tutorial

### ISSUE THREAD

**Issue by jorgearanda** [jorgearanda/fish#96]
Instead of (or in addition to) displaying instructions, participants could be shown a tutorial that explains how to fish, what the information on the panes means, etc.

**Comment by James-Firth** [comment]
Did a quick search and these libraries looked the best (might require some styling and depends on what licenses are compatible with fish). Commenting so everyone can look and comment on these libraries at some point and so I don't lose all the links.

https://github.com/heelhook/chardin.js 

http://clu3.github.io/bootstro.js/

https://github.com/usablica/intro.js 

http://linkedin.github.io/hopscotch/

**Comment by nsue** [comment]
Oh! This looks like fun to implement.

**Comment by jorgearanda** [comment]
Excellent. And this reminds me that I need to make the license explicit—I'll do so now.

**Comment by James-Firth** [comment]
Sounds good! 

I'm somewhat familiar with licenses, but unclear on the intricacies of license compatibility.... Obviously MIT works with MIT, but can we use GPL or Apache licensed libraries? (Since those two seem to come up the most)

**Comment by jorgearanda** [comment]
I'm not an expert, but my understanding is that GPL can be used in MIT projects, though said projects could from then on not be used or recombined as propietary software. I believe BSD and MIT are compatible.

**Comment by jorgearanda** [comment]
Hey Randi—do you think we could have a first go at this on a PR soon? :-)
